This checkin adds 2 new build modes: 1. --enable-engine-only lets you build just the engine 2. --enable-server-components-only lets you just build the engine,mdserver,vcl (the server-side components)
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/branches/1.12RC/src@7467 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS TOPDIR PLATFORM_CPPFLAGS SUBDIRS ALLSUBDIRS SRC BUILD_DBIO_ONLY NON_DBIO_SERLIBS NON_DBIO_PARLIBS CMAKE CXXFLAGS EGREP CXX LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT PARALLEL PARALLEL_CPPFLAGS MPI_LIBS MPI_CC MPI_CXX LIBSTATICPAR LIBSHAREDPAR LIBSHAREDPAR_UPDATEONLY PARDEP BUILD_COGNOMEN LIBCOGNOMEN MESA_DIR MESA_INCLUDE MESA_LIBS VIEWER_MESA_STUB_CPPFLAGS VIEWER_MESA_LIBS BUILD_MESA_STUB ICET_CXXFLAGS ICET_LDFLAGS ICET_LIBS ICET_ENG_MAIN_OBJ CC CFLAGS ac_ct_CC GL_LIBS VTK_DIR VTK_INCLUDES VTK_LIBS VTK_LIGHTWEIGHT_LIBS AVTPREP_SER AVTPREP_PAR CONVERT_SER CONVERT_PAR MAKEMILI_SER MAKEMILI_PAR ENGINE_SER ENGINE_PAR ENGINELIBSER ENGINELIBPAR METADATA_SERVER MDSERVERLIB MDSERVEROBJ VISITPY SCRIPTINGLIB SCRIPTINGOBJ PY_BUILD_VISITMODULE VIEWER VISWINDOW VIEWERLIB VIEWEROBJ VIEWERLIB_SRC VIEWEREXE_SRC ENGINEPROXYDIR GUI GUILIB GUIOBJ GUIFRAMEWORKS ANNOTATION_FLAGS JAVAC JAVA_TARGET JAR JAVAFLAGS JAVAPLUGINFLAGS BUILD_SLIVR SLIVR_INCLUDE SLIVR_LIBS TEEM_CMAKE_C_FLAGS SLIVR_CMAKE_SHARED_LINKER_FLAGS SLIVR_GUI_IMPL SLIVR_GUI_HDR HELP PLOT_BUILD_DIRS OPERATOR_BUILD_DIRS DB_BUILD_DIRS BUILD_GLEW GLEW_INCLUDE GLEW_LIBS BUILD_BILIB VISITWRAPPER_RPATH CXXCPP CPP F77 FFLAGS ac_ct_F77 SET_MAKE RANLIB ac_ct_RANLIB MAKEDEPEND BUILD_FORTRAN OS_RULE BUILD_ZLIB ZLIB_LIB HDF5_INCLUDE HDF5_LIB HDF5_TARGET SILO_INCLUDE SILO_LIB SILO_TARGET EXODUS EXODUS_LIB EXODUS_LIBS EXODUS_FLAGS PDB PDB_FLAGS PDB_LIBS PDB_EXEC MILI MILI_FLAGS MILI_LIBS MILI_DIR TCMALLOC_LIB TCMALLOC_DIR CREATE_TCMALLOC_LINK HDF4 HDF4_FLAGS HDF4_LIBS HDF4_LIBDIR BOXLIB2D BOXLIB2D_INCLUDE BOXLIB2D_LIBS BOXLIB2D_LIBDIR BOXLIB3D BOXLIB3D_INCLUDE BOXLIB3D_LIBS BOXLIB3D_LIBDIR H5PART H5PART_INCLUDE H5PART_LIB H5PART_LIBDIR FASTBIT FASTBIT_INCLUDE FASTBIT_LIB FASTBIT_LIBDIR VISUS VISUS_INCLUDE VISUS_LIB NETCDF NETCDF_INCLUDE NETCDF_LIB NETCDF_CXX_LIB CGNS CGNS_INCLUDE CGNS_LIB GDAL GDAL_INCLUDE GDAL_LIB GDAL_LIBS CFITSIO CFITSIO_INCLUDE CFITSIO_LIB CFITSIO_LIBDIR ITAPS_C_INCLUDE ITAPS_C_LIB ITAPS_C0_INCLUDE ITAPS_C0_LIB ITAPS_C1_INCLUDE ITAPS_C1_LIB ITAPS_C2_INCLUDE ITAPS_C2_LIB ITAPS_C3_INCLUDE ITAPS_C3_LIB ITAPS_C4_INCLUDE ITAPS_C4_LIB ITAPS_C CCMIO CCMIO_INCLUDE CCMIO_LIBS CCMIO_LIBDIR SIMULATION EXPORT_DYNAMIC ENGINE_CPPFLAGS SILOOBJVTK_CPPFLAGS PREPROCESSOR_CPPFLAGS PREPROCESSOR_PARALLEL_SRC COMPONENT_CPPFLAGS VISIT_VTK_CPPFLAGS VISIT_VTK_LDFLAGS VIEWER_CPPFLAGS QT_BIN QT_INCLUDE QT_LIB LIBQT QT_LIBS QUI_LIBS QT_LDFLAGS QT_STATICLDFLAGS QT_CXXFLAGS QT_MOC X_LIBS VTKQT_CPPFLAGS VTKQT VTKQT_LIBS PTHREAD_LIB PTHREAD_CXXFLAGS PYDIR PYVERSION PY_INCLUDEDIR PY_CXXFLAGS PY_LDFLAGS PY_LIB PY_CLI_LIB EXE_LDFLAGS PLUGIN_LDFLAGS DATA_EXE_LDFLAGS SHLIB_CREATEPROG SHLIB_LIBS SHLIB_SERLIBS SHLIB_PARLIBS SHLIB_MPI_LIBS SHLIB_ILIBS SHLIB_GLIBS SHLIB_VLIBS SHLIB_MLIBS SHLIB_ESERLIBS SHLIB_EPARLIBS SHLIB_SLIBS SHLIB_POSTPROCESS_ILIBS SHLIB_POSTPROCESS_GLIBS SHLIB_POSTPROCESS_VLIBS SHLIB_POSTPROCESS_MLIBS SHLIB_POSTPROCESS_ESERLIBS SHLIB_POSTPROCESS_EPARLIBS SHLIB_POSTPROCESS_SLIBS SHLIB_SOEXT SHLIB_LIBEXT SHLIB_POSTPROCESS SHLIB_POSTPROCESS_SER SHLIB_POSTPROCESS_PAR SHLIB_TMPDIR PREBIND_LIBS ENGINEWRAPSER ENGINEWRAPPAR CREATE_SILO_LINK CREATE_MILI_LINK CREATE_HDF4_LINK CREATE_NETCDF_LINK CREATE_CGNS_LINK CREATE_GDAL_LINK CREATE_EXODUS_LINK CREATE_BOXLIB2D_LINK CREATE_BOXLIB3D_LINK CREATE_CFITSIO_LINK CREATE_H5PART_LINK CREATE_FASTBIT_LINK CREATE_CCMIO_LINK VAC_CV_LIBDIR_CREATE_LINKS VAC_CV_LIBDIR_DESTROY_LINKS MG tmpbin tmpinc tmplib plotplugindir operatorplugindir databaseplugindir DATA_REL_VISIT_PATH LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS TOPDIR PLATFORM_CPPFLAGS SUBDIRS ALLSUBDIRS SRC BUILD_DBIO_ONLY NON_DBIO_SERLIBS NON_DBIO_PARLIBS CMAKE CXXFLAGS EGREP CXX LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT PARALLEL PARALLEL_CPPFLAGS MPI_LIBS MPI_CC MPI_CXX LIBSTATICPAR LIBSHAREDPAR LIBSHAREDPAR_UPDATEONLY PARDEP BUILD_COGNOMEN LIBCOGNOMEN MESA_DIR MESA_INCLUDE MESA_LIBS VIEWER_MESA_STUB_CPPFLAGS VIEWER_MESA_LIBS BUILD_MESA_STUB ICET_CXXFLAGS ICET_LDFLAGS ICET_LIBS ICET_ENG_MAIN_OBJ CC CFLAGS ac_ct_CC GL_LIBS VTK_DIR VTK_INCLUDES VTK_LIBS VTK_LIGHTWEIGHT_LIBS AVTPREP_SER AVTPREP_PAR CONVERT_SER CONVERT_PAR MAKEMILI_SER MAKEMILI_PAR ENGINE_SER ENGINE_PAR ENGINELIBSER ENGINELIBPAR METADATA_SERVER MDSERVERLIB MDSERVEROBJ VISITPY SCRIPTINGLIB SCRIPTINGOBJ PY_BUILD_VISITMODULE VIEWER VIEWERLIB VIEWEROBJ VIEWERLIB_SRC VIEWEREXE_SRC ENGINEPROXYDIR GUI GUILIB GUIOBJ GUIFRAMEWORKS ANNOTATION_FLAGS JAVAC JAVA_TARGET JAR JAVAFLAGS JAVAPLUGINFLAGS BUILD_SLIVR SLIVR_INCLUDE SLIVR_LIBS TEEM_CMAKE_C_FLAGS SLIVR_CMAKE_SHARED_LINKER_FLAGS SLIVR_GUI_IMPL SLIVR_GUI_HDR HELP PLOT_BUILD_DIRS OPERATOR_BUILD_DIRS DB_BUILD_DIRS BUILD_GLEW GLEW_INCLUDE GLEW_LIBS BUILD_BILIB VISITWRAPPER_RPATH CXXCPP CPP F77 FFLAGS ac_ct_F77 SET_MAKE RANLIB ac_ct_RANLIB MAKEDEPEND BUILD_FORTRAN XML2MAKEFILE_CXX OS_RULE BUILD_ZLIB ZLIB_LIB HDF5_INCLUDE HDF5_LIB HDF5_TARGET SILO_INCLUDE SILO_LIB SILO_TARGET EXODUS EXODUS_LIB EXODUS_LIBS EXODUS_FLAGS PDB PDB_FLAGS PDB_LIBS PDB_EXEC MILI MILI_FLAGS MILI_LIBS MILI_DIR TCMALLOC_LIB TCMALLOC_DIR CREATE_TCMALLOC_LINK HDF4 HDF4_FLAGS HDF4_LIBS HDF4_LIBDIR BOXLIB2D BOXLIB2D_INCLUDE BOXLIB2D_LIBS BOXLIB2D_LIBDIR BOXLIB3D BOXLIB3D_INCLUDE BOXLIB3D_LIBS BOXLIB3D_LIBDIR H5PART H5PART_INCLUDE H5PART_LIB H5PART_LIBDIR FASTBIT FASTBIT_INCLUDE FASTBIT_LIB FASTBIT_LIBDIR VISUS VISUS_INCLUDE VISUS_LIB NETCDF NETCDF_INCLUDE NETCDF_LIB NETCDF_CXX_LIB CGNS CGNS_INCLUDE CGNS_LIB GDAL GDAL_INCLUDE GDAL_LIB GDAL_LIBS CFITSIO CFITSIO_INCLUDE CFITSIO_LIB CFITSIO_LIBDIR ITAPS_C_INCLUDE ITAPS_C_LIB ITAPS_C0_INCLUDE ITAPS_C0_LIB ITAPS_C1_INCLUDE ITAPS_C1_LIB ITAPS_C2_INCLUDE ITAPS_C2_LIB ITAPS_C3_INCLUDE ITAPS_C3_LIB ITAPS_C4_INCLUDE ITAPS_C4_LIB ITAPS_C CCMIO CCMIO_INCLUDE CCMIO_LIBS CCMIO_LIBDIR SIMULATION EXPORT_DYNAMIC ENGINE_CPPFLAGS SILOOBJVTK_CPPFLAGS PREPROCESSOR_CPPFLAGS PREPROCESSOR_PARALLEL_SRC COMPONENT_CPPFLAGS VISIT_VTK_CPPFLAGS VISIT_VTK_LDFLAGS VIEWER_CPPFLAGS QT_BIN QT_INCLUDE QT_LIB LIBQT QT_LIBS QUI_LIBS QT_LDFLAGS QT_STATICLDFLAGS QT_CXXFLAGS QT_MOC X_LIBS VTKQT_CPPFLAGS VTKQT VTKQT_LIBS PTHREAD_LIB PTHREAD_CXXFLAGS PYDIR PYVERSION PY_INCLUDEDIR PY_CXXFLAGS PY_LDFLAGS PY_LIB PY_CLI_LIB EXE_LDFLAGS PLUGIN_LDFLAGS DATA_EXE_LDFLAGS SHLIB_CREATEPROG SHLIB_LIBS SHLIB_SERLIBS SHLIB_PARLIBS SHLIB_MPI_LIBS SHLIB_ILIBS SHLIB_GLIBS SHLIB_VLIBS SHLIB_MLIBS SHLIB_ESERLIBS SHLIB_EPARLIBS SHLIB_SLIBS SHLIB_POSTPROCESS_ILIBS SHLIB_POSTPROCESS_GLIBS SHLIB_POSTPROCESS_VLIBS SHLIB_POSTPROCESS_MLIBS SHLIB_POSTPROCESS_ESERLIBS SHLIB_POSTPROCESS_EPARLIBS SHLIB_POSTPROCESS_SLIBS SHLIB_SOEXT SHLIB_LIBEXT SHLIB_POSTPROCESS SHLIB_POSTPROCESS_SER SHLIB_POSTPROCESS_PAR SHLIB_TMPDIR PREBIND_LIBS ENGINEWRAPSER ENGINEWRAPPAR CREATE_SILO_LINK CREATE_MILI_LINK CREATE_HDF4_LINK CREATE_NETCDF_LINK CREATE_CGNS_LINK CREATE_GDAL_LINK CREATE_EXODUS_LINK CREATE_BOXLIB2D_LINK CREATE_BOXLIB3D_LINK CREATE_CFITSIO_LINK CREATE_H5PART_LINK CREATE_FASTBIT_LINK CREATE_CCMIO_LINK VAC_CV_LIBDIR_CREATE_LINKS VAC_CV_LIBDIR_DESTROY_LINKS MG tmpbin tmpinc tmplib plotplugindir operatorplugindir databaseplugindir DATA_REL_VISIT_PATH LIBOBJS LTLIBOBJS'
 ac_subst_files='VARIABLES TARGETS DIRTARGETS LIBTARGETS PARLIBTARGETS SOURCE_DEPENDENCIES'
 
 # Initialize some variables set by options.
@@ -867,6 +867,10 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --enable-dbio-only      build only the components necessary to support
                           database I/O
+  --enable-engine-only    build only the compute engine
+  --enable-server-components-only
+                          build only the server components
+                          (engine,mdserver,vcl)
   --enable-fake-exceptions       do not make use of C++'s exception library
   --enable-ignore-hangups        ignore hangup signals (this avoids RHEL3 bug)
   --enable-parallel       make the parallel version
@@ -874,7 +878,6 @@ Optional Features:
   --enable-icet           Use the ICE-T parallel image compositor
 
   --disable-ogl           do not check for the SGI ogl library
-  --disable-mdserver      build without mdserver
   --disable-scripting     build without CLI Python scripting capability
   --enable-visitmodule    build a VisIt Python module
   --disable-annotations   build without annotations
@@ -1598,6 +1601,39 @@ else
 fi
 
 
+
+#
+# Check for engine-only build. Disable clients,etc. Just build the engine.
+#
+# Check whether --enable-engine-only or --disable-engine-only was given.
+if test "${enable_engine_only+set}" = set; then
+  enableval="$enable_engine_only"
+
+fi;
+if test "$enable_engine_only" = yes && test "$enable_dbio_only" = yes; then
+   { { echo "$as_me:$LINENO: error: --enable-dbio-only is not compatible with --enable-engine-only" >&5
+echo "$as_me: error: --enable-dbio-only is not compatible with --enable-engine-only" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+#
+# Check for server-components-only build. Disable clients,etc. Just build the engine,mdserver,vcl.
+#
+# Check whether --enable-server-components-only or --disable-server-components-only was given.
+if test "${enable_server_components_only+set}" = set; then
+  enableval="$enable_server_components_only"
+
+fi;
+if test "$enable_server_components_only" = yes && test "$enable_dbio_only" = yes; then
+   { { echo "$as_me:$LINENO: error: --enable-server-components-only is not compatible with --enable-engine-only" >&5
+echo "$as_me: error: --enable-server-components-only is not compatible with --enable-engine-only" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test "$enable_server_components_only" = yes && test "$enable_engine_only" = yes; then
+   { echo "$as_me:$LINENO: WARNING: --enable-server-components-only overrides --enable-engine-only" >&5
+echo "$as_me: WARNING: --enable-server-components-only overrides --enable-engine-only" >&2;}
+   enable_engine_only=no
+fi
 
 #
 # Check for CMake
@@ -2493,7 +2529,7 @@ else
   UseViewerMesaStub=yes
 fi;
 
-if test "$UseViewerMesaStub" = "yes"; then
+if test "$UseViewerMesaStub" = "yes" && test ! "$enable_engine_only" = yes && test ! "$enable_server_components_only" = yes ; then
    echo "$as_me:$LINENO: result: enabled" >&5
 echo "${ECHO_T}enabled" >&6
    VIEWER_MESA_STUB_CPPFLAGS="-DMESA_STUB"
@@ -3759,20 +3795,6 @@ fi
 
 
 
-#
-# Check for the common directory
-#
-echo "$as_me:$LINENO: checking for common" >&5
-echo $ECHO_N "checking for common... $ECHO_C" >&6
-if test -d common; then
-    echo "$as_me:$LINENO: result: found" >&5
-echo "${ECHO_T}found" >&6
-    COMMON="common"
-else
-    echo "$as_me:$LINENO: result: not found" >&5
-echo "${ECHO_T}not found" >&6
-    COMMON=""
-fi
 
 #
 # Check for the avtprep directory
@@ -3886,21 +3908,9 @@ fi
 
 
 #
-# Check to see if the mdserver was enabled.
+# The mdserver is enabled unless we're doing an engine-only build.
 #
-echo "$as_me:$LINENO: checking if mdserver is enabled" >&5
-echo $ECHO_N "checking if mdserver is enabled... $ECHO_C" >&6
-# Check whether --enable-mdserver or --disable-mdserver was given.
-if test "${enable_mdserver+set}" = set; then
-  enableval="$enable_mdserver"
-  UseMDSERVER="$enable_mdserver"
-else
-  UseMDSERVER=yes
-fi;
-if test "$UseMDSERVER" = "yes"; then
-    echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
+if test ! "$enable_engine_only" = yes; then
                 echo "$as_me:$LINENO: checking for mdserver" >&5
 echo $ECHO_N "checking for mdserver... $ECHO_C" >&6
     if test -d mdserver; then
@@ -3915,8 +3925,6 @@ echo "${ECHO_T}not found" >&6
         METADATA_SERVER=""
     fi
 else
-    echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
     METADATA_SERVER=""
 fi
 
@@ -3935,7 +3943,7 @@ if test "${enable_scripting+set}" = set; then
 else
   UseScripting=yes
 fi;
-if test "X$UseScripting" = "Xyes"; then
+if test "X$UseScripting" = "Xyes" && test ! "$enable_engine_only" = yes && test ! "$enable_server_components_only" = yes; then
     echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
     enable_scripting=yes
@@ -3979,13 +3987,8 @@ fi
 
 
 
-echo "$as_me:$LINENO: checking for viewer" >&5
-echo $ECHO_N "checking for viewer... $ECHO_C" >&6
-if test -d viewer; then
-    echo "$as_me:$LINENO: result: found" >&5
-echo "${ECHO_T}found" >&6
+if test ! "$enable_engine_only" = yes && test ! "$enable_server_components_only" = yes; then
     VIEWER="viewer"
-    VISWINDOW="VisWindow"
     VIEWERLIB="$""(VDSO)"
     VIEWEROBJ="$""(VOBJ)"
     # The private source can go into the executable on all UNIX versions
@@ -4000,7 +4003,6 @@ echo "${ECHO_T}found" >&6
     ENGINEPROXYDIR="proxy"
 else
     VIEWER=""
-    VISWINDOW=""
     VIEWERLIB=""
     VIEWEROBJ=""
     VIEWERLIB_SRC=""
@@ -4014,12 +4016,7 @@ fi
 
 
 
-
-echo "$as_me:$LINENO: checking for gui" >&5
-echo $ECHO_N "checking for gui... $ECHO_C" >&6
-if test -d gui; then
-    echo "$as_me:$LINENO: result: found" >&5
-echo "${ECHO_T}found" >&6
+if test ! "$enable_engine_only" = yes && test ! "$enable_server_components_only" = yes; then
     GUI="gui"
     GUILIB="$""(GDSO)"
     GUIOBJ="$""(GOBJ)"
@@ -4029,8 +4026,6 @@ echo "${ECHO_T}found" >&6
         GUIFRAMEWORKS=""
     fi
 else
-    echo "$as_me:$LINENO: result: not found" >&5
-echo "${ECHO_T}not found" >&6
     GUI=""
     GUILIB=""
     GUIOBJ=""
@@ -6034,7 +6029,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:6037:" \
+echo "$as_me:6032:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6464,6 +6459,14 @@ if test $emptycxxflags = "yes"; then
         CXXFLAGS="-O2 $CXXFLAGS"
     fi
 fi
+
+# Give the option of using a different C++ compiler for xml2makefile since we
+# might want to give the local C++ compiler to generate a local tool, even if
+# we're cross-compiling
+if test -z "$XML2MAKEFILE_CXX"; then
+    XML2MAKEFILE_CXX="$""(CXX)"
+fi
+
 
 # Check to see if we're running clearmake.
 # If we are, set the build verbosity to 0 so that output won't mess up the rest
@@ -9958,7 +9961,7 @@ fi
 #
 # Only enable VTKQT if we're building the viewer.
 #
-if test ! "$enable_dbio_only" = yes; then
+if test ! "$enable_dbio_only" = yes && test ! "$enable_engine_only" = yes && test ! "$enable_server_components_only" = yes; then
    VTKQT_CPPFLAGS="-I$""(TOPDIR)/vtkqt"
    VTKQT="vtkqt"
    #
@@ -19487,6 +19490,74 @@ if test "$enable_dbio_only" = yes; then
         avt/Database/Makefile
         avt/Pipeline/Makefile"
 fi
+if test "$enable_engine_only" = yes; then
+    CONVERT_SER=""
+    CONVERT_PAR=""
+    SUBDIRS="$""(SUBDIRS_ENGINE_ONLY)"
+    ALLSUBDIRS="$""(ALLSUBDIRS_ENGINE_ONLY)"
+#    SRC="$""(SRC_ENGINE_ONLY)"
+    GUI_FILES=""
+    HELP_FILES=""
+    WINUTIL_FILES=""
+    VIEWER_FILES=""
+    MDSERVER_FILES=""
+    LAUNCHER_FILES=""
+    VTKQT_FILES=""
+    VISITPY_FILES=""
+    CQSCORE_FILES=""
+    JAVA_FILES=""
+    TOOLS_FILES=""
+    COMPONENT_FILES="avt/Makefile
+                 avt/DBAtts/Makefile
+                 avt/DDF/Makefile
+                 avt/Database/Makefile
+                 avt/Expressions/Makefile
+                 avt/FileWriter/Makefile
+                 avt/Filters/Makefile
+                 avt/IVP/Makefile
+                 avt/Math/Makefile
+                 avt/MIR/Makefile
+                 avt/Pipeline/Makefile
+                 avt/Plotter/Makefile
+                 avt/Preprocessor/Makefile
+                 avt/Queries/Makefile
+                 avt/Shapelets/Makefile
+                 avt/View/Makefile
+                 avt/VisWindow/Makefile"
+fi
+if test "$enable_server_components_only" = yes; then
+    CONVERT_SER=""
+    CONVERT_PAR=""
+    SUBDIRS="$""(SUBDIRS_SERVER_COMPONENTS_ONLY)"
+    ALLSUBDIRS="$""(ALLSUBDIRS_SERVER_COMPONENTS_ONLY)"
+#    SRC="$""(SRC_SERVER_COMPONENTS_ONLY)"
+    GUI_FILES=""
+    HELP_FILES=""
+    WINUTIL_FILES=""
+    VIEWER_FILES=""
+    VTKQT_FILES=""
+    VISITPY_FILES=""
+    CQSCORE_FILES=""
+    JAVA_FILES=""
+    TOOLS_FILES=""
+    COMPONENT_FILES="avt/Makefile
+                 avt/DBAtts/Makefile
+                 avt/DDF/Makefile
+                 avt/Database/Makefile
+                 avt/Expressions/Makefile
+                 avt/FileWriter/Makefile
+                 avt/Filters/Makefile
+                 avt/IVP/Makefile
+                 avt/Math/Makefile
+                 avt/MIR/Makefile
+                 avt/Pipeline/Makefile
+                 avt/Plotter/Makefile
+                 avt/Preprocessor/Makefile
+                 avt/Queries/Makefile
+                 avt/Shapelets/Makefile
+                 avt/View/Makefile
+                 avt/VisWindow/Makefile"
+fi
 
                                                                                                                                                                                                                             ac_config_files="$ac_config_files $STANDARD_FILES $GUI_FILES $HELP_FILES $WINUTIL_FILES $VIEWER_FILES $ENGINE_FILES $MDSERVER_FILES $LAUNCHER_FILES $COMMON_FILES $TOOLS_FILES $VISIT_VTK_FILES $VTKQT_FILES $COMPONENT_FILES $PLOT_FILES $OPERATOR_FILES $DATABASE_FILES $DATA_FILES $VISITPY_FILES $SIMULATION_PROTOTYPE_FILES $CQSCORE_FILES $THIRD_PARTY_BUILTIN_FILES $JAVA_FILES"
           ac_config_commands="$ac_config_commands default"
@@ -20190,7 +20261,6 @@ s,@SCRIPTINGLIB@,$SCRIPTINGLIB,;t t
 s,@SCRIPTINGOBJ@,$SCRIPTINGOBJ,;t t
 s,@PY_BUILD_VISITMODULE@,$PY_BUILD_VISITMODULE,;t t
 s,@VIEWER@,$VIEWER,;t t
-s,@VISWINDOW@,$VISWINDOW,;t t
 s,@VIEWERLIB@,$VIEWERLIB,;t t
 s,@VIEWEROBJ@,$VIEWEROBJ,;t t
 s,@VIEWERLIB_SRC@,$VIEWERLIB_SRC,;t t
@@ -20232,6 +20302,7 @@ s,@RANLIB@,$RANLIB,;t t
 s,@ac_ct_RANLIB@,$ac_ct_RANLIB,;t t
 s,@MAKEDEPEND@,$MAKEDEPEND,;t t
 s,@BUILD_FORTRAN@,$BUILD_FORTRAN,;t t
+s,@XML2MAKEFILE_CXX@,$XML2MAKEFILE_CXX,;t t
 s,@OS_RULE@,$OS_RULE,;t t
 s,@BUILD_ZLIB@,$BUILD_ZLIB,;t t
 s,@ZLIB_LIB@,$ZLIB_LIB,;t t
