2.3.1 release

diff --git a/svn_bin/build_visit b/svn_bin/build_visit
--- a/svn_bin/build_visit
+++ b/svn_bin/build_visit
@@ -409,6 +409,31 @@
 #     Eric Brugger, Fri Jun 17 13:19:14 PDT 2011
 #     I changed the visit version number to 2.3.0.
 #
+#     Eric Brugger, Tue Jul 19 08:51:29 PDT 2011
+#     I added some flags to the qt configure line that speeds up the compile.
+#     The changes were provided by Jens Henrik.
+#
+#     Eric Brugger, Wed Jul 20 11:36:38 PDT 2011
+#     I changed the visit version number to 2.3.1.
+#
+#     Eric Brugger, Thu Jul 21 08:25:52 PDT 2011
+#     I changed the display of the last message so that the entire message
+#     was visible when the script is run in graphical mode. The message was
+#     about 20 lines and only the last line was being displayed. I added an
+#     info_box_large function that displays many lines and then used that
+#     to display the last message.
+#
+#     Eric Brugger, Thu Jul 21 11:44:14 PDT 2011
+#     I changed the behavior of the script when the user specifies the third
+#     party library directory and the directory doesn't exist. It used to
+#     print an error message and exit, now it prompts the user to determine
+#     if it should create the directory and only exits with an error if the
+#     user indicates that the script shouldn't create the directory.
+#
+#     Eric Brugger, Fri Jul 22 09:18:05 PDT 2011
+#     With Jean Favre's help, I modified the script so that it would build
+#     VisIt on Ubuntu 11.04.
+#
 # *****************************************************************************
 
 
@@ -739,7 +764,7 @@ fi
 # release tag.
 ############################################################################
 
-export VISIT_VERSION=${VISIT_VERSION:-"2.3.0"}
+export VISIT_VERSION=${VISIT_VERSION:-"2.3.1"}
 
 ####
 # Trunk:
@@ -946,6 +971,7 @@ export ICET_BUILD_DIR=${ICET_BUILD_DIR:-"IceT-1-0-0"}
 DLG="dialog"
 DLG_BACKTITLE="VisIt $VISIT_VERSION Build Process"
 DLG_HEIGHT="5"
+DLG_HEIGHT_TALL="25"
 DLG_WIDTH="60"
 DLG_WIDTH_WIDE="80"
 
@@ -1000,6 +1026,9 @@ function warn
 # Programmer: Tom Fogal                                                       #
 # Date: Fri Oct  3 09:37:51 MDT 2008                                          #
 #                                                                             #
+# Modifications:                                                              #
+#    Jeremy Meredith, Fri Jul 22 10:36:20 EDT 2011                            #
+#    Added a little more text to help users.                                  #
 # *************************************************************************** #
 
 function error
@@ -1008,7 +1037,9 @@ function error
     if test "${LOG_FILE}" != "/dev/tty" ; then
         warn "Error in build process.  See ${LOG_FILE} for more information."\
              "If the error is unclear, please include ${LOG_FILE} in a "\
-             "message to the visit-users list." 
+             "message to the visit-users@ornl.gov list.  You will probably "\
+             "need to compress the ${LOG_FILE} using a program like gzip "\
+             "so it will fit within the size limits for email attachments."
     fi
     exit 1
 }
@@ -1034,7 +1065,7 @@ function info_box
 # *************************************************************************** #
 # Function: info                                                              #
 #                                                                             #
-# Purpose: Given an informative message to the user.                          #
+# Purpose: Give an informative message to the user.                           #
 #                                                                             #
 # Programmer: Tom Fogal                                                       #
 # Date: Fri Oct  3 09:41:50 MDT 2008                                          #
@@ -1060,6 +1091,24 @@ function info
         # write message to log as well
         log "$@"
     fi
+}
+
+# *************************************************************************** #
+# Function: info_box_large                                                    #
+#                                                                             #
+# Purpose: Show a large information box with a message.                       #
+#                                                                             #
+# Programmer: Eric Brugger,                                                   #
+# Date: Thu Jul 21 08:25:52 PDT 2011                                          #
+#                                                                             #
+# *************************************************************************** #
+
+function info_box_large
+{
+    if [[ "$GRAPHICAL" == "yes" ]] ; then
+        $DLG --backtitle "$DLG_BACKTITLE" --infobox "$1" $DLG_HEIGHT_TALL $DLG_WIDTH
+    fi
+    return 0
 }
 
 # *************************************************************************** #
@@ -1150,6 +1199,10 @@ function uncompress_untar
 #   Eric Brugger, Mon Jan 10 16:00:13 PST 2011                                #
 #   I made it always fall back to anonymous svn checkout.                     #
 #                                                                             #
+#   Eric Brugger, Tue Jul 19 10:19:50 PDT 2011                                #
+#   I made it use the anonymous svn site as the fallback download site        #
+#   instead of llnl's web site.                                               #
+#                                                                             #
 # *************************************************************************** #
 
 function download_file
@@ -1220,8 +1273,8 @@ function download_file
         rm -f $dfile
     fi
 
-    # Now try visit's 3rd_party.
-    try_download_file https://wci.llnl.gov/codes/visit/3rd_party/$dfile $dfile
+    # Now try the anonymous svn site with wget or curl.
+    try_download_file $SVN_ANON_ROOT_PATH/trunk/third_party/$dfile $dfile
     if [[ $? == 0 ]] ; then
         return 0
     fi
@@ -3303,6 +3356,11 @@ function build_qt
     qt_flags="${qt_flags} -no-libtiff"
     qt_flags="${qt_flags} -no-libjpeg"
     qt_flags="${qt_flags} -no-webkit"
+    qt_flags="${qt_flags} -nomake docs" 
+    qt_flags="${qt_flags} -nomake examples" 
+    qt_flags="${qt_flags} -nomake demos" 
+    qt_flags="${qt_flags} -opensource" 
+    qt_flags="${qt_flags} -confirm-license"
     if [[ ${QT_VERSION} == 4.6.1 ]] ; then
         qt_flags="${qt_flags} -no-javascript-jit"
         qt_flags="${qt_flags} -no-script"
@@ -3409,6 +3467,59 @@ function build_qt
 #                          Function 5, build_cmake                            #
 # *************************************************************************** #
 
+function apply_cmake_patch_1
+{
+   patch -p0 <<\EOF
+diff -c a/Modules/Platform/UnixPaths.cmake cmake-2.8.3/Modules/Platform/UnixPaths.cmake
+*** a/Modules/Platform/UnixPaths.cmake
+--- cmake-2.8.3/Modules/Platform/UnixPaths.cmake
+***************
+*** 67,72 ****
+--- 67,75 ----
+    /usr/pkg/lib
+    /opt/csw/lib /opt/lib
+    /usr/openwin/lib
++
++   # Ubuntu 11.04
++   /usr/lib/x86_64-linux-gnu
+    )
+
+  LIST(APPEND CMAKE_SYSTEM_PROGRAM_PATH
+***************
+*** 75,80 ****
+--- 78,86 ----
+
+  LIST(APPEND CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES
+    /lib /usr/lib /usr/lib32 /usr/lib64
++
++   # Ubuntu 11.04
++   /usr/lib/x86_64-linux-gnu
+    )
+
+  LIST(APPEND CMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES
+EOF
+   if [[ $? != 0 ]] ; then
+        warn "Unable to apply patch 1 to cmake."
+        return 1
+   else
+        return 0
+   fi
+}
+
+
+function apply_cmake_patch
+{
+   info "Patching CMake . . ."
+
+   apply_cmake_patch_1
+   if [[ $? != 0 ]] ; then
+      return 1
+   fi
+
+   return 0
+}
+
+
 function build_cmake
 {
     #
@@ -3419,6 +3530,22 @@ function build_cmake
     if [[ $untarred_cmake == -1 ]] ; then
        warn "Unable to prepare CMake build directory. Giving Up!"
        return 1
+    fi
+
+    #
+    # Patch cmake
+    #
+    apply_cmake_patch
+    if [[ $? != 0 ]] ; then
+       if [[ $untarred_cmake == 1 ]] ; then
+          warn "Giving up on CMake build because the patch failed."
+          return 1
+       else
+          warn "Patch failed, but continuing.  I believe that this script\n"\
+               "tried to apply a patch to an existing directory which had\n"\
+               "already been patched ... that is, that the patch is\n"\
+               "failing harmlessly on a second application."
+       fi
     fi
 
     #
@@ -8026,8 +8153,8 @@ function build_xdmf
     rm CML.*
     mv CMakeLists.txt CML.0
     H5DIR=$(echo "$VISITDIR/hdf5/$HDF5_VERSION/$VISITARCH" | sed "s/\//\\\\\//g")
-    sed "s/  hdf5/  hdf5  $H5DIR\/lib/g" CML.0 > CML.1
-    sed "s/H5Ipublic.h/H5Ipublic.h $H5DIR\/include/g" CML.1 > CMakeLists.txt
+    sed "s/  hdf5/  hdf5  $H5DIR\/lib NO_DEFAULT_PATH/g" CML.0 > CML.1
+    sed "s/H5Ipublic.h/H5Ipublic.h $H5DIR\/include NO_DEFAULT_PATH/g" CML.1 > CMakeLists.txt
 
     # Configure Xdmf
     info "Executing CMake on Xdmf"
@@ -8038,6 +8165,18 @@ function build_xdmf
         XDMF_SHARED_LIBS="ON"
         LIBEXT="${SO_EXT}"
     fi
+    if [[ "$OPSYS" == "Darwin" ]]; then
+        # Work around build problems on Mac.
+        XDMF_ZLIB_OPTIONS="-DXDMF_SYSTEM_ZLIB:BOOL=OFF"
+        cd Utilities/vtklibxml2
+        rm CML.*
+        mv CMakeLists.txt CML.0
+        sed "s/SET(LIBXML2_LIBS \"\")/SET(LIBXML2_LIBS \"vtkzlib\")/g" CML.0 > CML.1
+        sed "s/SET(WITH_MODULES 1)/SET(WITH_MODULES 0)/g" CML.1 > CMakeLists.txt
+        cd ../..
+    else
+        XDMF_ZLIB_OPTIONS="-DXDMF_SYSTEM_ZLIB:BOOL=ON"
+    fi
     ${CMAKE_BIN} -DCMAKE_INSTALL_PREFIX:PATH="$VISITDIR/Xdmf/${XDMF_VERSION}/${VISITARCH}"\
         -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON \
         -DBUILD_SHARED_LIBS:BOOL=${XDMF_SHARED_LIBS}\
@@ -8047,10 +8186,10 @@ function build_xdmf
         -DCMAKE_C_COMPILER:STRING=${C_COMPILER}\
         -DBUILD_TESTING:BOOL=OFF \
         -DXDMF_BUILD_MPI:BOOL=OFF \
-        -DXDMF_BUILD_UTILS:BOOL=OFF \
         -DXDMF_BUILD_VTK:BOOL=OFF \
+        -DXDMF_BUILD_UTILS:BOOL=OFF \
+        ${XDMF_ZLIB_OPTIONS}\
         -DXDMF_SYSTEM_HDF5:BOOL=ON \
-        -DXDMF_SYSTEM_ZLIB:BOOL=ON \
         .
 
     if [[ $? != 0 ]] ; then
@@ -8080,8 +8219,11 @@ function build_xdmf
     # Patch up the library names on Darwin
     if [[ "$DO_STATIC_BUILD" != "yes" && "$OPSYS" == "Darwin" ]]; then
         LIBDIR="$VISITDIR/Xdmf/${XDMF_VERSION}/${VISITARCH}/lib"
-        install_name_tool -change libvtklibxml2.dylib $LIBDIR/libvtklibxml2.dylib -id $LIBDIR/libXdmf.dylib $LIBDIR/libXdmf.dylib 
-        install_name_tool -id $LIBDIR/libvtklibxml2.dylib $LIBDIR/libvtklibxml2.dylib 
+        install_name_tool -change libvtklibxml2.dylib $LIBDIR/libvtklibxml2.dylib \
+                          -change libvtkzlib.dylib $VISITDIR/vtk/${VTK_VERSION}/${VISITARCH}/lib/libvtkzlib.dylib \
+                          -id $LIBDIR/libXdmf.dylib $LIBDIR/libXdmf.dylib 
+        install_name_tool -change libvtkzlib.dylib $VISITDIR/vtk/${VTK_VERSION}/${VISITARCH}/lib/libvtkzlib.dylib \
+                          -id $LIBDIR/libvtklibxml2.dylib $LIBDIR/libvtklibxml2.dylib 
     fi
 
     if [[ "$DO_GROUP" == "yes" ]] ; then
@@ -8724,6 +8866,17 @@ function build_hostconf
         >> $HOSTCONF
     fi
     echo >> $HOSTCONF
+
+    #
+    # Patch for Ubuntu 11.04
+    #
+    if test -d "/usr/lib/x86_64-linux-gnu" ; then
+        rm -f $HOSTCONF.tmp
+        cat $HOSTCONF | sed "s/\/usr\/lib/\/usr\/lib\/x86_64-linux-gnu/" > $HOSTCONF.tmp
+        rm $HOSTCONF
+        mv $HOSTCONF.tmp $HOSTCONF
+    fi
+
     cd "$START_DIR"
     echo "Done creating $HOSTCONF"
     return 0
@@ -9827,8 +9980,32 @@ if [[ "$DOWNLOAD_ONLY" == "no" ]] ; then
                   "Bailing out."
          fi
       else
-         error "The location to install the third party libraries does not exist." \
-               "Bailing out"
+         if [[ "$GRAPHICAL" == "yes" ]] ; then
+             $DLG --backtitle "$DLG_BACKTITLE" --yesno "The third party library location does not exist. Create it?" 0 0
+             if [[ $? == 1 ]] ; then
+                 error "The third party library location does not exist." \
+                       "Bailing out."
+             else
+                 mkdir "$THIRD_PARTY_PATH"
+                 if [[ $? != 0 ]] ; then
+                    error "Unable to write files to the third party library location." \
+                          "Bailing out."
+                 fi
+             fi
+         else
+             info "The third party library location does not exist. Create it?"
+             read RESPONSE
+             if [[ "$RESPONSE" != "yes" ]] ; then
+                 error "The third party library location does not exist." \
+                       "Bailing out."
+             else
+                 mkdir "$THIRD_PARTY_PATH"
+                 if [[ $? != 0 ]] ; then
+                    error "Unable to write files to the third party library location." \
+                          "Bailing out."
+                 fi
+             fi
+         fi
       fi
    fi
 
@@ -10411,31 +10588,70 @@ if [[ "$DO_VISIT" == "yes" ]] ; then
     if [[ $? != 0 ]] ; then
         error "Unable to build or install VisIt.  Bailing out."
     fi
-    info "Done building VisIt"
+
     if [[ "$DO_SVN" == "yes" && "$USE_VISIT_FILE" == "no" ]] ; then
-        info \
-        "You may now try to run VisIt by cd'ing into the src/bin"
+        VISIT_SRC_DIR="src"
     else
-        info \
-        "You may now try to run VisIt by cd'ing into the ${VISIT_FILE%.tar*}/src/bin"
+        VISIT_SRC_DIR="${VISIT_FILE%.tar*}/src"
     fi
-    info "directory and invoking \"visit\"."
-    info
-    info "To create a binary distribution tarball from this build, cd to"
-    if [[ "$DO_SVN" == "yes" && "$USE_VISIT_FILE" == "no" ]] ; then
-        info "${START_DIR}/src"
+
+FINISHED_MSG="Finished building VisIt.\n\n\
+You many now try to run VisIt by cd'ing into the \
+$VISIT_SRC_DIR/bin directory and invoking \"visit\".\n\n\
+To create a binary distribution tarball from this build, cd to \
+${START_DIR}/${VISIT_SRC_DIR}\n\
+then enter: \"make package\"\n\n\
+This will produce a tarball called visitVERSION.ARCH.tar.gz, where \
+VERSION is the version number, and ARCH is the OS architecure.\n\n\
+To install the above tarball in a directory called \"INSTALL_DIR_PATH\",\
+enter: svn_bin/visit-install VERSION ARCH INSTALL_DIR_PATH\n\n\
+If you run into problems, contact visit-users@ornl.gov."
+
+    #
+    # Output the message indicating that we are finished. I couldn't get
+    # the imbedded newlines in the FINISHED_MSG to display properly so I
+    # am treating the graphical and console interfaces differently.
+    #
+    if test "${GRAPHICAL}" = "yes" ; then
+        if [[ "$REDIRECT_ACTIVE" == "yes" ]] ; then
+            info_box_large "$FINISHED_MSG" 1>&3
+        else
+            info_box_large "$FINISHED_MSG"
+        fi
+        log "Finished building VisIt."
+        log
+        log "You many now try to run VisIt by cd'ing into the"
+        log "$VISIT_SRC_DIR/bin directory and invoking \"visit\""
+        log
+        log "To create a binary distribution tarball from this build, cd to"
+        log "${START_DIR}/${VISIT_SRC_DIR}"
+        log "then enter: \"make package\""
+        log
+        log "This will produce a tarball called visitVERSION.ARCH.tar.gz, where"
+        log "VERSION is the version number, and ARCH is the OS architecure."
+        log
+        log "To install the above tarball in a directory called \"INSTALL_DIR_PATH\""
+        log "enter: svn_bin/visit-install VERSION ARCH INSTALL_DIR_PATH"
+        log
+        log "If you run into problems, contact visit-users@ornl.gov."
     else
-        info "${START_DIR}/${VISIT_FILE%.tar*}/src"
+        info "Finished building VisIt."
+        info
+        info "You many now try to run VisIt by cd'ing into the"
+        info "$VISIT_SRC_DIR/bin directory and invoking \"visit\""
+        info
+        info "To create a binary distribution tarball from this build, cd to"
+        info "${START_DIR}/${VISIT_SRC_DIR}"
+        info "then enter: \"make package\""
+        info
+        info "This will produce a tarball called visitVERSION.ARCH.tar.gz, where"
+        info "VERSION is the version number, and ARCH is the OS architecure."
+        info
+        info "To install the above tarball in a directory called \"INSTALL_DIR_PATH\""
+        info "enter: svn_bin/visit-install VERSION ARCH INSTALL_DIR_PATH"
+        info
+        info "If you run into problems, contact visit-users@ornl.gov."
     fi
-    info "then enter: \"make package\""
-    info
-    info "This will produce a tarball called visitVERSION.ARCH.tar.gz, where"
-    info "VERSION is the version number, and ARCH is the OS architecure."
-    info
-    info "To install the above tarball in a directory called "INSTALL_DIR_PATH","
-    info "enter: svn_bin/visit-install VERSION ARCH INSTALL_DIR_PATH"
-    info
-    info "If you run into problems, contact visit-users@ornl.gov"
 else
     if [[ $ANY_ERRORS == "no" ]] ; then
         info "Finished!"
