Add support for FastBit.
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/branches/1.12RC/src@6130 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/svn_bin/build_visit b/svn_bin/build_visit
--- a/svn_bin/build_visit
+++ b/svn_bin/build_visit
@@ -60,6 +60,7 @@
 #           CFITSIO  3006     cfitsio3006.tar.gz     -f
 #           CGNS     2.4.3    cgnslib_2.4-3.tar.gz   -c
 #           ExodusII 4.46     exodusii-4.46.tar.gz   -e
+#           FastBit  0.9.9    fastbit-b0.9.9.tar.gz  -r
 #           GDAL     1.3.2    gdal-1.3.2.tar.gz      -g (no AIX)
 #           H5part   1.4.0    H5Part-1.4.0.tar.gz    -r
 #           HDF4     2.4.1    HDF4.2r1.tar.gz        -4
@@ -97,6 +98,7 @@
 #     Function 8.10, build_h5part:  build H5Part
 #     Function 8.11, build_ccmio:   build CCMIO
 #     Function 8.12, build_tcmalloc: build google-perftools/tcmalloc
+#     Function 8.13, build_fastbit: build FastBit
 #     Function 8, build_silo:       build Silo
 #     Function 9, build_hostconf:   build the config-site/host.conf file
 #     Function 9.1, build_visit:    build the VisIt source code
@@ -454,6 +456,10 @@
 #     Mark C. Miller, Tue Jan 20 12:30:49 PST 2009
 #     Added code for Silo install on Darwin to try a C++ compiler if a C
 #     compiler fails the link phase of the install.
+#
+#     Hank Childs, Mon Jan 26 15:57:02 PST 2009
+#     Add support for FastBit.
+#
 # *****************************************************************************
 #
 # *************************************************************************** #
@@ -621,6 +627,8 @@ parallel="no"
 ON_parallel="off"
 export DO_H5PART="no"
 export ON_H5PART="off"
+export DO_FASTBIT="no"
+export ON_FASTBIT="off"
 export DO_SVN="no"
 export ON_SVN="off"
 export DO_REVISION="no"
@@ -794,6 +802,10 @@ export H5PART_FILE=${H5PART_FILE-"H5Part-1.4.0.tar.gz"}
 export H5PART_VERSION=${H5PART_VERSION-"1.4.0"}
 export H5PART_COMPATIBILITY_VERSION=${H5PART_COMPATIBILITY_VERSION-"1.0"}
 export H5PART_DIR=${H5PART_DIR-"H5Part-1.4.0"}
+
+export FASTBIT_FILE=${FASTBIT_FILE-"fastbit-b0.9.9.tar.gz"}
+export FASTBIT_VERSION=${FASTBIT_VERSION-"0.9.9"}
+export FASTBIT_DIR=${FASTBIT_DIR-"fastbit-b0.9.9"}
 
 export CCMIO_FILE=${CCMIO_FILE-"libccmio-2.6.1.tar.gz"}
 export CCMIO_VERSION=${CCMIO_VERSION-"2.6.1"}
@@ -1469,6 +1481,26 @@ function check_optional_3rdparty
                 echo "Unable to build CGNS.  ${CGNS_FILE} not found."
                 DO_CGNS="no"
             fi
+        fi
+    fi
+    #
+    # FastBit
+    #
+    if [[ "$DO_FASTBIT" == "yes" ]] ; then
+        HAVE_FASTBIT_ALREADY="NO"
+        HAVE_FASTBIT_TARBALL="NO"
+        if [[ -d "$VISITDIR/fastbit/$FASTBIT_VERSION/$VISITARCH" || \
+           -d $FASTBIT_DIR ]] ; then
+           HAVE_FASTBIT_ALREADY="YES"
+        fi
+        if [[ -e ${FASTBIT_FILE%.gz} || -e ${FASTBIT_FILE} ]] ; then
+           HAVE_FASTBIT_TARBALL="YES"
+        fi
+        if [[ "$HAVE_FASTBIT_ALREADY" = "NO" && \
+              "$HAVE_FASTBIT_TARBALL" = "NO" ]] ; then
+            log "FastBit is not available for download from the VisIt build site"
+            error "Try going to https://codeforge.lbl.gov/frs/?group_id=44"
+            DO_FASTBIT="no"
         fi
     fi
     #
@@ -7499,6 +7531,76 @@ function build_tcmalloc
     cp .libs/libtcmalloc.so* $VISITDIR/google-perftools/${TCMALLOC_VERSION}/$VISITARCH/lib
 }
 
+# *************************************************************************** #
+#                         Function 8.13, build_fastbit                        #
+# *************************************************************************** #
+
+function build_fastbit
+{
+    #
+    # Unzip the file, provided a gzipped file exists.
+    #
+    if [[ -d ${FASTBIT_DIR} ]] ; then
+       info_box "Found ${FASTBIT_DIR} . . ." 1>&3
+    elif [[ -f ${FASTBIT_FILE} ]] ; then
+       info_box "Unzipping/Tarring ${FASTBIT_FILE} . . ." 1>&3
+       uncompress_untar ${FASTBIT_FILE}
+       if [[ $? != 0 ]] ; then
+          echo \
+"Unable to untar ${FASTBIT_FILE}.  Corrupted file or out of space on device?"
+          return 1
+       fi
+    elif [[ -f ${FASTBIT_FILE%.*} ]] ; then
+       info_box "Tarring ${FASTBIT_FILE%.*} . . ." 1>&3
+       tar xf ${FASTBIT_FILE%.*}
+       if [[ $? != 0 ]] ; then
+          echo \
+"Unable to untar ${FASTBIT_FILE%.*}.  Corrupted file or out of space on device?"
+          return 1
+       fi
+    fi
+
+    #
+    info_box "Configuring FastBit . . ." 1>&3
+    cd ${FASTBIT_DIR}
+    echo "Invoking command to configure FastBit"
+    ./configure \
+       CXX="$CXX_COMPILER" CC="$C_COMPILER" \
+       CFLAGS="$C_OPT_FLAGS" CXXFLAGS="$CXX_OPT_FLAGS" \
+       --prefix="$VISITDIR/fastbit/$FASTBIT_VERSION/$VISITARCH" \
+       --disable-shared
+    if [[ $? != 0 ]] ; then
+       echo "FastBit configure failed.  Giving up"
+       return 1
+    fi
+
+    #
+    # Build FastBit
+    #
+    info_box "Building FastBit . . . (~7 minutes)" 1>&3
+    echo "Building FastBit"
+    $MAKE $MAKE_OPT_FLAGS
+    if [[ $? != 0 ]] ; then
+       echo "FastBit build failed.  Giving up"
+       return 1
+    fi
+    info_box "Installing FastBit . . ." 1>&3
+    echo "Installing FastBit"
+    $MAKE install
+    if [[ $? != 0 ]] ; then
+       echo "FastBit build (make install) failed.  Giving up"
+       return 1
+    fi
+
+    if [[ "$DO_GROUP" == "yes" ]] ; then
+       chmod -R ug+w,a+rX "$VISITDIR/fastbit"
+       chgrp -R ${GROUP} "$VISITDIR/fastbit"
+    fi
+    cd "$START_DIR"
+    echo "Done with FastBit"
+    return 0
+}
+
 
 # *************************************************************************** #
 #                          Function 9, build_hostconf                         #
@@ -7668,6 +7770,18 @@ function build_hostconf
         >> $HOSTCONF
         echo \
 "DEFAULT_H5PART_LIB=\$VISITHOME/h5part/$H5PART_VERSION/$VISITARCH/lib" \
+        >> $HOSTCONF
+    fi
+    echo >> $HOSTCONF
+    echo "##" >> $HOSTCONF
+    echo "## FastBit" >> $HOSTCONF
+    echo "##" >> $HOSTCONF
+    if [[ "$DO_FASTBIT" == "yes" ]] ; then
+        echo \
+"DEFAULT_FASTBIT_INCLUDE=\$VISITHOME/fastbit/$FASTBIT_VERSION/$VISITARCH/include" \
+        >> $HOSTCONF
+        echo \
+"DEFAULT_FASTBIT_LIB=\$VISITHOME/fastbit/$FASTBIT_VERSION/$VISITARCH/lib" \
         >> $HOSTCONF
     fi
     echo >> $HOSTCONF
@@ -8036,6 +8150,10 @@ printvariables () {
   printf "%s%s\n" "H5PART_COMPATIBILITY_VERSION=" "${H5PART_COMPATIBILITY_VERSION}"
   printf "%s%s\n" "H5PART_DIR=" "${H5PART_DIR}"
 
+  printf "%s%s\n" "FASTBIT_FILE=" "${FASTBIT_FILE}"
+  printf "%s%s\n" "FASTBIT_VERSION=" "${FASTBIT_VERSION}"
+  printf "%s%s\n" "FASTBIT_DIR=" "${FASTBIT_DIR}"
+
   printf "%s%s\n" "CCMIO_FILE=" "${CCMIO_FILE}"
   printf "%s%s\n" "CCMIO_VERSION=" "${CCMIO_VERSION}"
   printf "%s%s\n" "CCMIO_COMPATIBILITY_VERSION=" "${CCMIO_COMPATIBILITY_VERSION}"
@@ -8069,6 +8187,7 @@ usage () {
   printf "%-15s %s [%s]\n" "--console" "Do not use dialog ('graphical') interface" "!$GRAPHICAL"
   printf "%-15s %s [%s]\n" "--debug"   "Enable debugging for this script" "false"
   printf "%-15s %s [%s]\n" "--exodus" "Build Exodus" "$DO_EXODUS"
+  printf "%-15s %s [%s]\n" "--fastbit" "Build FastBit" "$DO_FASTBIT"
   printf "%-15s %s [%s]\n" "--flags-debug" "Add '-g' to C[XX]FLAGS" "false"
   printf "%-15s %s [%s]\n" "--gdal" "Build GDAL" "$DO_GDAL"
   printf "%-15s %s [%s]\n" "--group" "Group name of installed libraries" "$GROUP"
@@ -8274,6 +8393,8 @@ for arg in "${arguments[@]}" ; do
         --cxxflags) next_arg="cxxflags";;
         --console) GRAPHICAL="no"; ON_GRAPHICAL="off";;
         --debug) set -vx;;
+        --fastbit) DO_FASTBIT="yes"; ON_FASTBIT="on"
+                  DO_HDF5="yes"; ON_HDF5="on";;
         --exodus) DO_EXODUS="yes"; ON_EXODUS="on"
                   DO_NETCDF="yes"; ON_NETCDF="on";;
         --flags-debug) next_arg="flags-debug";;
@@ -8476,6 +8597,7 @@ if [[ "$DO_OPTIONAL" == "yes" && "$GRAPHICAL" == "yes" ]] ; then
            "CFITSIO"  "3006   $CFITSIO_FILE"   $ON_CFITSIO \
            "CGNS"     "2.4.3  $CGNS_FILE"      $ON_CGNS \
            "ExodusII" "4.46   $EXODUS_FILE"    $ON_EXODUS \
+           "FastBit"  "0.99   $FASTBIT_FILE"   $ON_FASTBIT \
            "GDAL"     "1.3.2  $GDAL_FILE"      $ON_GDAL \
            "H5Part"   "1.3.3  $H5PART_FILE"    $ON_H5PART \
            "HDF4"     "2.4.1  $HDF4_FILE"      $ON_HDF4 \
@@ -8494,6 +8616,7 @@ if [[ "$DO_OPTIONAL" == "yes" && "$GRAPHICAL" == "yes" ]] ; then
         DO_CFITSIO="no"
         DO_CGNS="no"
         DO_EXODUS="no"
+        DO_FASTBIT="no"
         DO_GDAL="no"
         DO_H5PART="no"
         DO_HDF4="no"
@@ -8515,6 +8638,9 @@ if [[ "$DO_OPTIONAL" == "yes" && "$GRAPHICAL" == "yes" ]] ; then
               ExodusII)
                  DO_EXODUS="yes"
                  DO_NETCDF="yes";;
+              FastBit)
+                 DO_HDF5="yes"
+                 DO_FASTBIT="yes";;
               GDAL)
                  DO_GDAL="yes";;
               H5Part)
@@ -9025,6 +9151,24 @@ if [[ "$DO_H5PART" == "yes" ]] ; then
          exit 1
       fi
       echo "Done building H5Part"
+   fi
+fi
+cd "$START_DIR"
+if [[ "$DO_FASTBIT" == "yes" ]] ; then
+   if [[ -d "$VISITDIR/fastbit/${FASTBIT_VERSION}/$VISITARCH" ]] ; then
+      echo "Skipping FastBit build.  FastBit is already installed."
+   else
+      echo "Building FastBit (~7 minutes)"
+      build_fastbit 3>&1 >> ${LOG_FILE} 2>&1
+      if [[ $? != 0 ]] ; then
+         echo "Unable to build or install FastBit.  Bailing out."
+         if [[ "${LOG_FILE}" != "/dev/tty" ]] ; then
+            echo \
+"More information about the failed build can be found in \"${LOG_FILE}\""
+         fi
+         exit 1
+      fi
+      echo "Done building FastBit"
    fi
 fi
 cd "$START_DIR"
