Made PIL download from LLNL's 3rd_party dir, and fixed the failure test.
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/branches/1.10RC/src@5255 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/svn_bin/build_visit b/svn_bin/build_visit
--- a/svn_bin/build_visit
+++ b/svn_bin/build_visit
@@ -397,6 +397,9 @@
 #     Hank Childs, Thu Aug 28 10:11:34 PDT 2008
 #     Make szip build on FC9.  (szip is required for HDF5.)
 #
+#     Tom Fogal, Thu Oct  2 11:53:37 MDT 2008
+#     Made PIL download from LLNL's 3rd_party dir, and fixed the failure test.
+#
 # *****************************************************************************
 #
 # *************************************************************************** #
@@ -3589,8 +3592,8 @@ CXX=\"$CXX_COMPILER\" CC=\"$C_COMPILER\" \
 
     if ! test -f ${PIL_FILE} ; then
         info_box "Downloading PIL ..." 1>&3
-        download_file ${PIL_URL}
-        if test $? -ne 0 ; then
+        download_3rdparty ${PIL_FILE}
+        if test $? -eq 0 ; then
             return 1
         fi
     fi
