Updated H5Part to 1.4.2 in DaVinci configuration. Updated H5Part to 1.4.2 and FastBit to 1.0.8 in build_visit to meet requirements of updated HDF_UC database plugin. In build_bisit, download FastBit automatically from LBNL CodeForge if no TAR ball present.
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/branches/1.12RC/src@7238 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/svn_bin/build_visit b/svn_bin/build_visit
--- a/svn_bin/build_visit
+++ b/svn_bin/build_visit
@@ -62,7 +62,7 @@
 #           ExodusII 4.46     exodusii-4.46.tar.gz   -e
 #           FastBit  0.9.9    fastbit-b0.9.9.tar.gz  -r
 #           GDAL     1.3.2    gdal-1.3.2.tar.gz      -g (no AIX)
-#           H5part   1.4.0    H5Part-1.4.0.tar.gz    -r
+#           H5part   1.4.2    H5Part-1.4.2.tar.gz    -r
 #           HDF4     2.4.1    HDF4.2r1.tar.gz        -4
 #           HDF5     1.8.1    hdf5-1.8.1.tar.gz      -5
 #           Mili     1.10     mili-1.10a.tar.gz      -m (internal)
@@ -483,6 +483,11 @@
 #     Tom Fogal, Sun Mar 22 20:00:46 MST 2009
 #     Correct an earlier patch I had made to PPC HDF4 -- thanks P.S.
 #
+#     Gunther H. Weber, Thu May  7 11:20:50 PDT 2009
+#     Update H5Part to 1.4.2 and FastBit to 1.0.8 as required by changes
+#     to the HDF_UC database plugin. Download FastBit automatically from
+#     LBNL Codeforge if TAR ball not present.
+#
 # *****************************************************************************
 #
 # *************************************************************************** #
@@ -826,14 +831,15 @@ export CFITSIO_VERSION=${CFITSIO_VERSION-"3006"}
 export CFITSIO_COMPATIBILITY_VERSION=${CFITSIO_COMPATIBILITY_VERSION-"3.0"}
 export CFITSIO_DIR=${CFITSIO_DIR-"cfitsio"}
 
-export H5PART_FILE=${H5PART_FILE-"H5Part-1.4.0.tar.gz"}
-export H5PART_VERSION=${H5PART_VERSION-"1.4.0"}
-export H5PART_COMPATIBILITY_VERSION=${H5PART_COMPATIBILITY_VERSION-"1.0"}
-export H5PART_DIR=${H5PART_DIR-"H5Part-1.4.0"}
+export H5PART_FILE=${H5PART_FILE-"H5Part-1.4.2.tar.gz"}
+export H5PART_VERSION=${H5PART_VERSION-"1.4.2"}
+export H5PART_COMPATIBILITY_VERSION=${H5PART_COMPATIBILITY_VERSION-"1.4"}
+export H5PART_DIR=${H5PART_DIR-"H5Part-1.4.2"}
 
-export FASTBIT_FILE=${FASTBIT_FILE-"fastbit-b0.9.9.tar.gz"}
-export FASTBIT_VERSION=${FASTBIT_VERSION-"0.9.9"}
-export FASTBIT_DIR=${FASTBIT_DIR-"fastbit-b0.9.9"}
+export FASTBIT_URL=${FASTBIT_URL-"https://codeforge.lbl.gov/frs/download.php/45/fastbit-ibis1.0.8.tar.gz"}
+export FASTBIT_FILE=${FASTBIT_FILE-"fastbit-ibis1.0.8.tar.gz"}
+export FASTBIT_VERSION=${FASTBIT_VERSION-"1.0.8"}
+export FASTBIT_DIR=${FASTBIT_DIR-"fastbit-ibis1.0.8"}
 
 export CCMIO_FILE=${CCMIO_FILE-"libccmio-2.6.1.tar.gz"}
 export CCMIO_VERSION=${CCMIO_VERSION-"2.6.1"}
@@ -1526,9 +1532,12 @@ function check_optional_3rdparty
         fi
         if [[ "$HAVE_FASTBIT_ALREADY" = "NO" && \
               "$HAVE_FASTBIT_TARBALL" = "NO" ]] ; then
-            log "FastBit is not available for download from the VisIt build site"
-            error "Try going to https://codeforge.lbl.gov/frs/?group_id=44"
-            DO_FASTBIT="no"
+            echo "Downloading FastBit"
+            webget ${FASTBIT_URL}
+            if [[ $? == 0 ]] ; then
+                echo "Unable to bulild FastBit. ${FASTBIT_FILE} not found at ${FASTBIT_URL}."
+                DO_FASTBIT="no"
+            fi
         fi
     fi
     #
@@ -9326,6 +9335,7 @@ if [[ "$DO_H5PART" == "yes" ]] ; then
    fi
 fi
 cd "$START_DIR"
+echo DO_FASTBIT=$DO_FASTBIT
 if [[ "$DO_FASTBIT" == "yes" ]] ; then
    if [[ -d "$VISITDIR/fastbit/${FASTBIT_VERSION}/$VISITARCH" ]] ; then
       echo "Skipping FastBit build.  FastBit is already installed."
