fixing problem where build_visit fails to install Silo on Darwin due to use of C compiler to link code with C++ dependencies
git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/branches/1.11RC/src@6033 18c085ea-50e0-402c-830e-de6fd14e8384

diff --git a/svn_bin/build_visit b/svn_bin/build_visit
--- a/svn_bin/build_visit
+++ b/svn_bin/build_visit
@@ -451,6 +451,9 @@
 #     Eric Brugger, Mon Dec 29 15:07:09 PST 2008
 #     Changed the version to 1.11.2.
 #
+#     Mark C. Miller, Tue Jan 20 12:30:49 PST 2009
+#     Added code for Silo install on Darwin to try a C++ compiler if a C
+#     compiler fails the link phase of the install.
 # *****************************************************************************
 #
 # *************************************************************************** #
@@ -4304,6 +4307,17 @@ qt -lSM -lICE -L/usr/X11R6/lib -lX11 -lXext -lXmu -lXt -lXi"
            -Wl,-install_name,$INSTALLNAMEPATH/libsilo${SILO_H5}.${SO_EXT} \
            -Wl,-compatibility_version,${SILO_COMPATIBILITY_VERSION} \
            -Wl,-current_version,${SILO_VERSION} $SILO_LINK_OPT
+        #
+        # The above could have failed in libsilo has C++ code (from hzip/fpzip)
+        # So, in that case, try it with a C++ compiler too.
+        #
+        if [[ $? != 0 ]] ; then
+            $CXX_COMPILER -dynamiclib -o libsilo${SILO_H5}.${SO_EXT} *.o \
+               -Wl,-headerpad_max_install_names \
+               -Wl,-install_name,$INSTALLNAMEPATH/libsilo${SILO_H5}.${SO_EXT} \
+               -Wl,-compatibility_version,${SILO_COMPATIBILITY_VERSION} \
+               -Wl,-current_version,${SILO_VERSION} $SILO_LINK_OPT
+        fi
         if [[ $? != 0 ]] ; then
            echo "Silo dynamic library build failed.  Giving up"
            return 1
